persistence:
  size: 10Gi

replicaCount: 3 

auth:
  username: admin
  password: admin

extraPlugins: "rabbitmq_auth_backend_ldap rabbitmq_consistant_hash_exchange rabbitmq_federation rabbitmq_federation_management rabbitmq_sharding rabbitmq_shovel rabbitmq_shovel_management"
